# Generated by Django 4.2.3 on 2023-08-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("target", models.IntegerField()),
                ("actual", models.IntegerField()),
                ("points", models.IntegerField()),
            ],
        ),
    ]
