# Generated by Django 4.2.3 on 2023-08-03 03:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_employeedata"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmployeeData",
        ),
    ]
