# Generated by Django 4.2.3 on 2023-08-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SensorData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sensor_id", models.IntegerField()),
                ("sensor_name", models.CharField(max_length=100)),
                ("mon_avg_count", models.IntegerField()),
                ("tue_avg_count", models.IntegerField()),
                ("wed_avg_count", models.IntegerField()),
                ("thu_avg_count", models.IntegerField()),
                ("fri_avg_count", models.IntegerField()),
                ("sat_avg_count", models.IntegerField()),
                ("sun_avg_count", models.IntegerField()),
                ("date", models.DateField()),
            ],
        ),
    ]
